apiVersion: v1
kind: Service
metadata:
  name: wbsic-backend
  namespace: production
  labels:
    app: wbsic-backend
spec:
  selector:
    app: wbsic-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      name: http
  type: ClusterIP
