apiVersion: v1
kind: Service
metadata:
  name: wbsic-frontend
  namespace: production
  labels:
    app: wbsic-frontend
spec:
  selector:
    app: wbsic-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      name: http
  type: ClusterIP