apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: wbsic-backend-pdb
  namespace: production
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: wbsic-backend

# 
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: wbsic-frontend-pdb
  namespace: production
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: wbsic-frontend